---
anubis_version: "1.25.0"
anubis_base_path: "/opt/anubis"
anubis_bin_path: "{{ anubis_base_path }}/bin"
anubis_state: "present"

anubis_os_name: "linux"
anubis_architecture: "amd64"

anubis_service: "gitea"
