---
snipe_it_user: snipeit
snipe_it_version: "8.3.5"
snipe_it_domain: ~
snipe_it_state: present
snipe_it_deployment_method: docker

snipe_it_env_file: /etc/snipeit/env
snipe_it_data_directory: /var/lib/snipeit
